aeternity/docker-builder

.circleci/config.yml
Dockerfile
README.md

Each PR creates and push docker image to docker hub with tag "ci-build-$BRANCH".
Master builds would push to "latest" tag.
Images are build in CircleCI.
see https://hub.docker.com/r/aetrnty/builder/tags/

Add initial Dockerfile

---

Dockerfile

https://www.pivotaltracker.com/story/show/155250917

Bump OTP version to 20.2.3

---

Dockerfile

Add python3 headers and pip3
In scope of [PT 155783725](https://www.pivotaltracker.com/story/show/155783725)

Improve python3 support

---

.circleci/config.yml
README.md

in scope of https://www.pivotaltracker.com/story/show/155940263

Change DockerHub org to "aeternity"

---

.circleci/config.yml

https://www.pivotaltracker.com/story/show/155857274

Don't double build docker image on master

---

Dockerfile

[Packer](https://www.packer.io)

Install packer

---

Dockerfile

add terraform

---

Dockerfile

Besides, erlang 21.0 is just released now. Will it be supported?

erlang 20.3.8

---

Dockerfile

Effectively finishes: https://www.pivotaltracker.com/story/show/158550692
Prove: https://circleci.com/workflow-run/4450cb21-0172-4249-bbf4-0e964796a149
Should be merged after: https://github.com/aeternity/epoch/pull/1373

Remove obsolete infrastructure dependencies

---

.circleci/config.yml
Dockerfile
package_ubuntu_18.04/Dockerfile

Add OTP 21.2.3 images

---

Dockerfile
package_ubuntu_18.04/Dockerfile

Reference: https://github.com/aeternity/rebar3/releases/tag/3.9.1-aeternity.1

Upgrade rebar3 to 3.9.1-aeternity.1

---

Dockerfile
package_ubuntu_18.04/Dockerfile

Reference: https://github.com/aeternity/rebar3/releases/tag/3.9.1-aeternity.2

Upgrade rebar3 to 3.9.1-aeternity.2

---

.circleci/config.yml

https://www.pivotaltracker.com/story/show/166116373

Use CI environments context

---

Dockerfile
package_ubuntu_18.04/Dockerfile

In scope of https://www.pivotaltracker.com/story/show/166546345

Upgrade rebar3 to latest stable one

---

.circleci/config.yml
Dockerfile
package_ubuntu_18.04/Dockerfile

Also updated rebar3 to 3.12.0 which is the latest version also being
used in aeternity itself.

Update OTP to the latest patch releases

---

.circleci/config.yml
Dockerfile

Upgrade OTP 20 and 21 to latest patch releases

---

.circleci/config.yml

rel https://github.com/aeternity/aeternity/issues/3293

OTP versions bump

---

.circleci/config.yml

Add otp-24 build to our suite of docker ci images

---

.circleci/config.yml

ESL only have debian packages up to 24.1.3, so use that one for now

Use earlier otp-24 version

---

.circleci/config.yml

- small re-factoring
- add build_2004_otp22 to commit workflow
- add build_2004_otp24 to release workflow

Revamp CI config 
